### ISSUE TITLE
external links in quick view do not open a new tab/window

### ISSUE THREAD

**Issue by nickvdmee** [stuartduff/wc-external-product-new-tab#1]
Hi Stuart,

Here is the quick view plug-in i use: [https://nl.wordpress.org/plugins/woocommerce-products-quick-view/](https://nl.wordpress.org/plugins/woocommerce-products-quick-view/)
I tried other quick view plug-ins as well and also tried other external products in new tab plug-ins to see if there is any combination that works, but i cant find it.
I prefer your plug-in over other external product plug-ins so that is why i wrote you.
Hopefully you can tell me how i can fix this (in combination with this current quick view plug-in would be awesome since it is really good).
Thank you in advance.

Regards,

Nick

**Comment by stuartduff** [comment]
Thanks @nickvdmee I will have a look and see what I can spot. :)

**Comment by nickvdmee** [comment]
Hi @stuartduff ,

Where you able to spot anything yet?

Regards, Nick

**Comment by stuartduff** [comment]
@nickvdmee sorry for the delay and will try and look into this over the coming weekend for you.

**Comment by stuartduff** [comment]
@nickvdmee looking at the quick view plugin for you it uses a custom external button template for it's products which the developer has hardcoded the url HTML into their plugin is why this is not working for you.

The function which is outputting this within their plugin is titled `external_add_to_cart()` and is located within their plugins `classes/class-quick-view-template.php` file.
